[package]
name = "concurrentes-tp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "local"
path = "local/src/main.rs"

[[bin]]
name = "e-commerce"
path = "e-commerce/src/main.rs"

[dependencies]
