name: ci

on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run fmt
        run: cargo fmt --all -- --check
      - name: Run check
        run: cargo check --all --color always
      - name: Run clippy
        run: cargo clippy --all -- -D warnings
      - name: Run test
        run: cargo test

